
#微服务实例名称
spring:
  application:
    name: cloud-eureka-server
#定义生效的配置文件名
  profiles:
    active: eureka2

---
#定义配置文件eureka1
spring:
  profiles: eureka1
#端口号
server:
  port: 8761
#eurekaserver集群注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

---
#定义配置文件eureka2
spring:
  profiles: eureka2
#端口号
server:
  port: 8762
#eurekaserver集群注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/