
#微服务实例名称
spring:
  application:
    name: cloud-eureka-server
#定义生效的配置文件名
  profiles:
    active: eureka1
#添加密码访问
  security:
    user:
      password: runningman7021
      name: runningman


---
#定义配置文件eureka1
spring:
  profiles: eureka1
#端口号
server:
  port: 8761
#eurekaserver集群注册地址
eureka:
  client:
    service-url:
    #eurekaserver用户验证后的注册地址更改：http://用户名：密码@localhost:8762/eureka/
      defaultZone: http://runningman:runningman7021@localhost:8762/eureka/

---
#定义配置文件eureka2
spring:
  profiles: eureka2
#端口号
server:
  port: 8762
#eurekaserver集群注册地址
eureka:
  client:
    service-url:
      defaultZone: http://runningman:runningman7021@localhost:8761/eureka/